# Development overrides
# Usage: docker compose -f docker-compose.yml -f docker-compose.dev.yml up

services:
  api:
    build:
      target: builder
    volumes:
      - ./api:/build
    environment:
      MERLON_ENV: development
      MERLON_LOG_LEVEL: debug
