.PHONY: help fmt fmt-check lint lint-go lint-ui verify-go verify-container-pins test test-go test-ui test-integration build build-go build-ui migrate audit-harden seed dev-up dev-down minimal-up minimal-down demogen generate-openapi docs-build docs-check

help: ## Show this help
	@grep -E '^[a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) | sort | awk 'BEGIN {FS = ":.*?## "}; {printf "\033[36m%-20s\033[0m %s\n", $$1, $$2}'

fmt: ## Format all code
	@cd api && go fmt ./...
	@cd ui && npx prettier --write "src/**/*.{ts,tsx}"

fmt-check: ## Check formatting without modifying files
	@files="$$(cd api && gofmt -l .)"; test -z "$$files" || (echo "Go files require gofmt:"; echo "$$files"; exit 1)

lint: fmt-check lint-go lint-ui ## Lint all code

lint-go: ## Run Go static analysis
	@cd api && go vet ./...

lint-ui: ## Run UI lint
	@cd ui && npm run lint

test: test-go test-ui ## Run all tests

GO_TEST_FLAGS ?=

test-go: ## Run Go tests
	@cd api && go test $(GO_TEST_FLAGS) ./...

test-ui: ## Run UI tests
	@cd ui && npm run test -- --run

test-integration: ## Apply migrations twice and run all Go tests against PostgreSQL
	@test -n "$${MERLON_MIGRATION_DATABASE_URL:-$${MERLON_DATABASE_URL:-}}" || (echo "MERLON_MIGRATION_DATABASE_URL or MERLON_DATABASE_URL is required"; exit 1)
	@$(MAKE) migrate
	@$(MAKE) migrate
	@cd api && go test -count=1 ./...

verify-go: fmt-check lint-go test-go build-go ## Run the complete Go verification gate

verify-container-pins: ## Verify repeated container image references stay synchronized
	@bash scripts/check-container-pins.sh

VERSION ?= $(shell git describe --tags --always 2>/dev/null || echo dev)

build: build-go build-ui ## Build all components

build-go: ## Build the Go API
	@cd api && go build -buildvcs=false -ldflags "-X main.version=$(VERSION)" ./cmd/merlon-api

build-ui: ## Build the operator UI
	@cd ui && npm run build

migrate: ## Apply SQL migrations with a versioned ledger (use a migration role)
	@cd api && go run ./cmd/merlon-migrate --migrations-dir ../migrations

audit-harden: ## Apply audit_logs least-privilege grants using a migration role
	@test -n "$${MERLON_MIGRATION_DATABASE_URL}" || (echo "MERLON_MIGRATION_DATABASE_URL is required"; exit 1)
	@psql "$${MERLON_MIGRATION_DATABASE_URL}" -v ON_ERROR_STOP=1 -v MERLON_APP_ROLE="$${MERLON_APP_ROLE:-merlon_app}" -f docs/operations/audit-hardening.sql

seed: ## Start the development topology with demo data
	@MERLON_SEED=true docker compose up --build

dev-up: ## Start development environment
	docker compose -f docker-compose.yml -f docker-compose.dev.yml up --build

dev-down: ## Stop development environment
	docker compose -f docker-compose.yml -f docker-compose.dev.yml down

minimal-up: ## Start minimal environment (PostgreSQL + API only)
	docker compose -f docker-compose.minimal.yml up --build

minimal-down: ## Stop minimal environment
	docker compose -f docker-compose.minimal.yml down

demogen: ## Generate synthetic demo data (deploy/seed/demo/*.json; not committed)
	@cd api && go run ./cmd/merlon-demogen -out ../deploy/seed/demo

generate-openapi: ## Export the OpenAPI spec to docs/api/openapi.json
	@cd api && go run ./cmd/openapi-export -o ../docs/api/openapi.json
	@# docs/api/openapi.md + docs/api/_category_.json are generated by
	@# website/scripts/generate-openapi-page.mjs, wired into the website's own
	@# `prebuild` (see website/package.json) so it always runs as part of
	@# `npm run build`, using the openapi.json this target just produced.

docs-build: generate-openapi ## Build the documentation site
	@cd website && (npm ci --no-audit --no-fund || npm install) && npm run build

docs-check: ## Run reproducible documentation check gates (language, titles, i18n parity/freshness, UI translations)
	@node website/scripts/checks/run-all.mjs
