.PHONY: help fmt fmt-check lint lint-go lint-ui audit-npm verify-go verify-container-pins verify-wrangler-pin verify-toolchain-pins verify-env-vars verify-openapi-coverage test test-go test-ui test-website test-scripts test-integration build build-go build-ui migrate backup restore audit-harden seed up down dev-up dev-down screenshots demogen generate-openapi docs-build docs-check

help: ## Show this help
	@grep -E '^[a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) | sort | awk 'BEGIN {FS = ":.*?## "}; {printf "\033[36m%-20s\033[0m %s\n", $$1, $$2}'

fmt: ## Format all code
	@cd api && go fmt ./...
	@cd ui && npx prettier --write "src/**/*.{ts,tsx}"

fmt-check: ## Check formatting without modifying files
	@files="$$(cd api && gofmt -l .)"; test -z "$$files" || (echo "Go files require gofmt:"; echo "$$files"; exit 1)

lint: fmt-check lint-go lint-ui ## Lint all code

lint-go: ## Run Go static analysis
	@cd api && go vet ./...

lint-ui: ## Run UI lint
	@cd ui && npm run lint

audit-npm: ## Check npm advisories against the recorded exceptions (same gate as CI)
	@node scripts/check-npm-audit.mjs ui website

test: test-go test-ui test-website test-scripts ## Run all tests

GO_TEST_FLAGS ?=

test-go: ## Run Go tests
	@cd api && go test $(GO_TEST_FLAGS) ./...

test-ui: ## Run UI tests
	@cd ui && npm run test -- --run

test-website: ## Run documentation generator script tests
	@cd website && npm run test:scripts

test-scripts: ## Run tests for the reference scripts (standard library only)
	@python3 -m unittest discover -s scripts -p 'test_*.py'

test-integration: ## Apply migrations twice and run all Go tests against PostgreSQL
	@test -n "$${MERLON_MIGRATION_DATABASE_URL:-$${MERLON_DATABASE_URL:-}}" || (echo "MERLON_MIGRATION_DATABASE_URL or MERLON_DATABASE_URL is required"; exit 1)
	@$(MAKE) migrate
	@$(MAKE) migrate
	@cd api && go test -count=1 ./...

verify-go: fmt-check lint-go test-go build-go ## Run the complete Go verification gate

verify-container-pins: ## Verify repeated container image references stay synchronized
	@bash scripts/check-container-pins.sh

verify-wrangler-pin: ## Verify the docs deploy workflow and website/package.json name the same Wrangler
	@bash scripts/check-wrangler-pin.sh

verify-env-vars: ## Verify env vars agree across the code, docs, and .env.example
	@bash scripts/check-env-vars.sh

verify-openapi-coverage: ## Verify the OpenAPI document still covers the registered API surface
	@python3 scripts/check-openapi-coverage.py

verify-toolchain-pins: ## Verify the build images, workflows, go.mod, and DevContainer name the same Go and Node.js
	@bash scripts/check-toolchain-pins.sh

VERSION ?= $(shell git describe --tags --always 2>/dev/null || echo dev)

build: build-go build-ui ## Build all components

build-go: ## Build the Go API
	@cd api && go build -buildvcs=false -ldflags "-X main.version=$(VERSION)" ./cmd/merlon-api

build-ui: ## Build the operator UI
	@cd ui && npm run build

migrate: ## Apply SQL migrations with a versioned ledger (use a migration role)
	@cd api && go run ./cmd/merlon-migrate --migrations-dir ../migrations

backup: ## Back up PostgreSQL and the encryption key ring (see scripts/backup.sh)
	@scripts/backup.sh $(BACKUP_DIR)

restore: ## Restore a backup produced by `make backup` (destructive; prompts)
	@test -n "$(BACKUP_FILE)" || (echo "BACKUP_FILE=path/to/merlon-db-*.dump is required"; exit 1)
	@scripts/restore.sh "$(BACKUP_FILE)"

audit-harden: ## Apply audit_logs least-privilege grants using a migration role
	@test -n "$${MERLON_MIGRATION_DATABASE_URL}" || (echo "MERLON_MIGRATION_DATABASE_URL is required"; exit 1)
	@psql "$${MERLON_MIGRATION_DATABASE_URL}" -v ON_ERROR_STOP=1 -v MERLON_APP_ROLE="$${MERLON_APP_ROLE:-merlon_app}" -f docs/operations/audit-hardening.sql

seed: ## Start the development topology with demo data
	@MERLON_SEED=true docker compose up --build

dev-up: ## Start development environment
	docker compose -f docker-compose.yml -f docker-compose.dev.yml up --build

dev-down: ## Stop development environment
	docker compose -f docker-compose.yml -f docker-compose.dev.yml down

up: ## Start the standard topology (PostgreSQL + API)
	docker compose up --build

down: ## Stop the standard topology
	docker compose down

screenshots: ## Capture docs/img demo UI screenshots (needs the demo stack running)
	@bash scripts/capture-screenshots.sh

demogen: ## Generate synthetic demo data (deploy/seed/demo/*.json; not committed)
	@cd api && go run ./cmd/merlon-demogen -out ../deploy/seed/demo

generate-openapi: ## Export the OpenAPI spec to docs/api/openapi.json
	@cd api && go run ./cmd/openapi-export -o ../docs/api/openapi.json
	@# docs/api/openapi.md + docs/api/_category_.json are generated by
	@# website/scripts/generate-openapi-page.mjs, wired into the website's own
	@# `prebuild` (see website/package.json) so it always runs as part of
	@# `npm run build`, using the openapi.json this target just produced.

docs-build: generate-openapi ## Build the documentation site
	@cd website && (npm ci --no-audit --no-fund || npm install) && npm run build

docs-check: ## Run reproducible documentation check gates (language, titles, i18n parity/freshness, UI translations)
	@node website/scripts/checks/run-all.mjs
