-- M2.2: Transactions and alerts tables for TM integration

CREATE TYPE transaction_direction AS ENUM ('inbound', 'outbound', 'internal');
CREATE TYPE alert_severity AS ENUM ('low', 'medium', 'high', 'critical');
CREATE TYPE alert_status AS ENUM ('open', 'investigating', 'escalated', 'closed_true_positive', 'closed_false_positive');

-- Transactions
CREATE TABLE transactions (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    customer_id UUID NOT NULL REFERENCES customers(id),
    external_id VARCHAR(255) NOT NULL,
    amount DECIMAL(18,2) NOT NULL,
    currency VARCHAR(3) NOT NULL DEFAULT 'JPY',
    direction transaction_direction NOT NULL,
    counterparty_id VARCHAR(255),
    counterparty_country VARCHAR(2),
    channel VARCHAR(100),
    executed_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT transactions_external_id_unique UNIQUE (external_id)
);

CREATE INDEX idx_transactions_customer ON transactions (customer_id, executed_at);
CREATE INDEX idx_transactions_executed_at ON transactions (executed_at);

-- Alerts generated by TM engine
CREATE TABLE alerts (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    customer_id UUID NOT NULL REFERENCES customers(id),
    scenario_id VARCHAR(255) NOT NULL,
    severity alert_severity NOT NULL,
    status alert_status NOT NULL DEFAULT 'open',
    score DECIMAL(5,2),
    description TEXT,
    transaction_ids UUID[] NOT NULL DEFAULT '{}',
    detected_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    resolved_at TIMESTAMPTZ,
    resolved_by VARCHAR(255),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_alerts_customer ON alerts (customer_id);
CREATE INDEX idx_alerts_status ON alerts (status);
CREATE INDEX idx_alerts_scenario ON alerts (scenario_id, detected_at);
CREATE INDEX idx_alerts_severity_status ON alerts (severity, status);
