-- WS-11 Task 8: optimistic locking (data-model.md §3.9).
--
-- cases.updated_at (migrations/004_cases.sql) and alerts.updated_at
-- (migrations/002_transactions_alerts.sql) already exist and already default
-- to NOW() on every row, so no new column is needed for cases/alerts:
-- api/internal/store's UpdateIfUnmodified / UpdateStatusIfUnmodified compare
-- a client-supplied expected_updated_at against the stored value with
-- `UPDATE ... WHERE id = $1 AND updated_at = $2`, returning zero affected
-- rows (translated to *domain.ErrConflict / HTTP 409) when another update
-- happened first.
--
-- rule_definitions.version (migrations/001_init.sql) already exists too;
-- its optimistic-lock API implementation is WS-2's responsibility, not this
-- workstream's -- this migration file exists only to record that no DDL
-- change was required here, so a later reader doesn't go looking for a
-- missing 022 migration.
