-- P03 / issue #99: durable source import run and per-record outcomes.
-- Derived AML artifacts are intentionally absent from this schema; imports
-- only persist source records and their auditable processing result.
CREATE TABLE IF NOT EXISTS import_runs (
    id uuid PRIMARY KEY,
    source_dir text NOT NULL,
    actor text NOT NULL DEFAULT '',
    mode text NOT NULL CHECK (mode IN ('dry_run', 'apply')),
    status text NOT NULL CHECK (status IN ('running', 'completed', 'failed')),
    source_files jsonb NOT NULL DEFAULT '{}'::jsonb,
    result_counts jsonb NOT NULL DEFAULT '{}'::jsonb,
    started_at timestamptz NOT NULL,
    completed_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS import_record_outcomes (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id uuid NOT NULL REFERENCES import_runs(id) ON DELETE CASCADE,
    entity_type text NOT NULL,
    external_id text NOT NULL,
    source_file text NOT NULL,
    line_number integer NOT NULL CHECK (line_number > 1),
    payload_sha256 text NOT NULL,
    status text NOT NULL CHECK (status IN ('accepted', 'skipped', 'rejected')),
    reason_code text NOT NULL DEFAULT '',
    created_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (run_id, entity_type, external_id, source_file, line_number)
);

CREATE INDEX IF NOT EXISTS import_record_outcomes_run_idx ON import_record_outcomes(run_id, id);
