-- P04 / issue #98: durable adapter checkpoint and sync-run state.
CREATE TABLE IF NOT EXISTS adapter_checkpoints (
    adapter_id text PRIMARY KEY,
    customer_cursor text NOT NULL DEFAULT '',
    transaction_cursor text NOT NULL DEFAULT '',
    customer_watermark text NOT NULL DEFAULT '',
    transaction_watermark text NOT NULL DEFAULT '',
    lease_owner text NOT NULL DEFAULT '',
    lease_until timestamptz,
    adapter_digest text NOT NULL DEFAULT '',
    updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS adapter_sync_runs (
    id uuid PRIMARY KEY,
    adapter_id text NOT NULL,
    status text NOT NULL CHECK (status IN ('running', 'completed', 'failed', 'partial')),
    adapter_digest text NOT NULL,
    started_at timestamptz NOT NULL,
    completed_at timestamptz,
    customer_accepted integer NOT NULL DEFAULT 0,
    customer_skipped integer NOT NULL DEFAULT 0,
    transaction_accepted integer NOT NULL DEFAULT 0,
    transaction_skipped integer NOT NULL DEFAULT 0,
    waiting_dependency integer NOT NULL DEFAULT 0,
    failed integer NOT NULL DEFAULT 0,
    checkpoint jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS adapter_sync_outcomes (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id uuid NOT NULL REFERENCES adapter_sync_runs(id) ON DELETE CASCADE,
    entity_type text NOT NULL,
    external_id text NOT NULL DEFAULT '',
    status text NOT NULL,
    reason text NOT NULL DEFAULT '',
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS adapter_sync_runs_adapter_idx ON adapter_sync_runs(adapter_id, started_at DESC);
CREATE INDEX IF NOT EXISTS adapter_sync_outcomes_run_idx ON adapter_sync_outcomes(run_id, id);
