-- P06 / issue #100: durable inbound push ingestion.
-- The payload is encrypted by the application before this table is touched;
-- only its digest is available for replay/conflict comparison.
ALTER TABLE customers ADD COLUMN IF NOT EXISTS source_updated_at timestamptz;

CREATE TABLE IF NOT EXISTS inbound_webhook_events (
    id text PRIMARY KEY,
    kind text NOT NULL CHECK (kind IN ('customers', 'transactions')),
    payload_digest text NOT NULL,
    payload_ciphertext text NOT NULL,
    record_count integer NOT NULL CHECK (record_count > 0 AND record_count <= 1000),
    status text NOT NULL CHECK (status IN ('accepted', 'running', 'completed', 'failed', 'dlq')),
    attempt_count integer NOT NULL DEFAULT 0 CHECK (attempt_count >= 0),
    next_attempt_at timestamptz NOT NULL,
    first_received_at timestamptz NOT NULL,
    last_attempt_at timestamptz,
    completed_at timestamptz,
    last_error text NOT NULL DEFAULT '',
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS inbound_webhook_events_due_idx
    ON inbound_webhook_events(status, next_attempt_at, id);

CREATE TABLE IF NOT EXISTS inbound_webhook_record_outcomes (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id text NOT NULL REFERENCES inbound_webhook_events(id) ON DELETE CASCADE,
    record_index integer NOT NULL CHECK (record_index >= 0),
    entity_type text NOT NULL,
    external_id text NOT NULL DEFAULT '',
    entity_id uuid,
    status text NOT NULL CHECK (status IN ('accepted', 'updated', 'skipped', 'waiting_dependency', 'rejected')),
    reason text NOT NULL DEFAULT '',
    created_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE(event_id, record_index)
);

CREATE INDEX IF NOT EXISTS inbound_webhook_record_outcomes_event_idx
    ON inbound_webhook_record_outcomes(event_id, record_index);
