// Shared helpers for the documentation check gates (website/scripts/checks/*.mjs).
//
// Every check is a deterministic script: same inputs -> same pass/fail
// result for anyone who runs it, independent of machine or invocation order.
// This module centralizes the path resolution, file walking, and small
// JSON/frontmatter parsers that all five checks need, so their skip rules
// (docs/api/**, docs/decisions/**) can't drift between checks.

import { execFileSync } from "node:child_process";
import { existsSync, readFileSync, readdirSync, statSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));

export const REPO_ROOT = path.resolve(__dirname, "..", "..", "..");
export const WEBSITE_DIR = path.join(REPO_ROOT, "website");
export const DOCS_DIR = path.join(REPO_ROOT, "docs");
export const JA_DOCS_DIR = path.join(
  WEBSITE_DIR,
  "i18n",
  "ja",
  "docusaurus-plugin-content-docs",
  "current"
);
export const DOCS_LINT_DIR = path.join(WEBSITE_DIR, "docs-lint");
export const FALLBACK_MANIFEST_PATH = path.join(
  WEBSITE_DIR,
  ".i18n-fallback-manifest.json"
);

// Same exclusion rule used across all checks: docs/api/** is generated
// (regenerated by the schema/openapi generators, gitignored), and
// docs/decisions/** (ADRs) and docs/standards/** (internal audit standards,
// written in Japanese) are intentionally excluded from the built site.
export const SKIP_PREFIXES = ["decisions/", "api/", "standards/"];

/** True if a SOURCE_DIR-relative (posix) path falls under a skipped prefix. */
export function isSkipped(relPath) {
  return SKIP_PREFIXES.some(
    (prefix) => relPath === prefix.replace(/\/$/, "") || relPath.startsWith(prefix)
  );
}

/** Convert a filesystem-relative path to the platform-independent posix form. */
export function toPosix(relPath) {
  return relPath.split(path.sep).join("/");
}

/** Recursively list every file under `dir` as sorted posix-style paths relative to `dir`. */
export function walk(dir, base = dir) {
  if (!existsSync(dir)) return [];
  const files = [];
  for (const entry of readdirSync(dir, { withFileTypes: true }).sort((a, b) =>
    a.name.localeCompare(b.name)
  )) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      files.push(...walk(full, base));
    } else if (entry.isFile()) {
      files.push(toPosix(path.relative(base, full)));
    }
  }
  return files.sort();
}

/** Hand-written Markdown docs under docs/: excludes docs/api/** and docs/decisions/**. */
export function listHandwrittenDocs() {
  return walk(DOCS_DIR).filter(
    (rel) => /\.mdx?$/.test(rel) && !isSkipped(rel)
  );
}

/** All *_category_.json files for hand-written directories under docs/. */
export function listHandwrittenCategoryFiles() {
  return walk(DOCS_DIR).filter(
    (rel) => path.basename(rel) === "_category_.json" && !isSkipped(rel)
  );
}

/** Read and JSON.parse a file, returning `fallback` if it does not exist. */
export function readJson(filePath, fallback) {
  if (!existsSync(filePath)) return fallback;
  return JSON.parse(readFileSync(filePath, "utf8"));
}

export function readFallbackManifest() {
  return readJson(FALLBACK_MANIFEST_PATH, []);
}

/**
 * Split a Markdown file's leading `---`-delimited frontmatter block from its
 * body. Returns `{ frontmatter: string|null, body: string }`; frontmatter is
 * null when the file has no (well-formed) frontmatter block.
 */
export function splitFrontmatter(content) {
  if (!content.startsWith("---")) return { frontmatter: null, body: content };
  const end = content.indexOf("\n---", 3);
  if (end === -1) return { frontmatter: null, body: content };
  const frontmatter = content.slice(3, end).replace(/^\n/, "");
  // Skip the closing "---" line and its newline.
  const afterClose = content.indexOf("\n", end + 1);
  const body = afterClose === -1 ? "" : content.slice(afterClose + 1);
  return { frontmatter, body };
}

/** Very small frontmatter parser: only handles flat `key: value` scalar lines. */
export function parseFrontmatterFields(frontmatter) {
  const fields = {};
  if (!frontmatter) return fields;
  for (const line of frontmatter.split("\n")) {
    const m = /^([A-Za-z0-9_]+):\s*(.*)$/.exec(line);
    if (!m) continue;
    let value = m[2].trim();
    if (
      (value.startsWith('"') && value.endsWith('"')) ||
      (value.startsWith("'") && value.endsWith("'"))
    ) {
      value = value.slice(1, -1);
    }
    fields[m[1]] = value;
  }
  return fields;
}

/** First Markdown ATX H1 (`# ...`) in a doc body, or null if none. */
export function firstH1(body) {
  const m = /^#\s+(.+?)\s*$/m.exec(body);
  return m ? m[1].trim() : null;
}

export const JP_CHAR_RE = /[぀-ヿ㐀-鿿ｦ-ﾟ]/;

export function containsJapanese(text) {
  return JP_CHAR_RE.test(text);
}

/** Git-tracked last-commit unix timestamp (seconds) for a file, or null if never committed. */
export function gitLastCommitTime(absPath) {
  try {
    const out = execFileSync(
      "git",
      ["log", "-1", "--format=%ct", "--", absPath],
      { cwd: REPO_ROOT, encoding: "utf8" }
    ).trim();
    return out ? Number(out) : null;
  } catch {
    return null;
  }
}

/** Git-tracked last-commit hash for a file, or null if never committed. */
export function gitLastCommitHash(absPath) {
  try {
    const out = execFileSync(
      "git",
      ["log", "-1", "--format=%H", "--", absPath],
      { cwd: REPO_ROOT, encoding: "utf8" }
    ).trim();
    return out || null;
  } catch {
    return null;
  }
}

/** True if `absPath` has uncommitted modifications/additions in `git status --porcelain`. */
export function gitHasUncommittedChanges(absPath) {
  try {
    const rel = toPosix(path.relative(REPO_ROOT, absPath));
    const out = execFileSync("git", ["status", "--porcelain", "--", rel], {
      cwd: REPO_ROOT,
      encoding: "utf8",
    });
    return out.trim().length > 0;
  } catch {
    return false;
  }
}

export function fileExists(p) {
  try {
    return statSync(p).isFile();
  } catch {
    return false;
  }
}

/** Sort violation objects deterministically by (file, then reason). */
export function sortViolations(violations) {
  return [...violations].sort((a, b) => {
    if (a.file !== b.file) return a.file < b.file ? -1 : 1;
    return a.reason < b.reason ? -1 : a.reason > b.reason ? 1 : 0;
  });
}
