import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * The docs sidebar is defined explicitly rather than autogenerated from the
 * directory tree.
 *
 * The directory layout groups pages by subject (compliance/, operations/,
 * development/), which is the right way to store them but says nothing about
 * *who* a page is for. Readers arriving at the site could not tell which
 * sections were written for compliance officers and which for developers.
 * The categories below are audience tracks instead, each ordered so it can be
 * read top to bottom, and they mirror the entry points offered on the
 * homepage (src/components/PersonaCards).
 *
 * Consequences of listing pages explicitly:
 *  - A new page under docs/ does not appear until it is added here. This is
 *    deliberate: placing a page means choosing its audience.
 *  - `sidebar_position` frontmatter and `_category_.json` files no longer
 *    affect ordering, except inside the autogenerated api/schema subtree
 *    (whose pages are generated, so their number varies).
 *  - Category labels are translated via the
 *    `sidebar.docsSidebar.category.<label>` keys in
 *    i18n/<locale>/docusaurus-plugin-content-docs/current.json.
 */
const sidebars: SidebarsConfig = {
  docsSidebar: [
    'index',
    {
      type: 'category',
      label: 'Understand Merlon',
      collapsed: false,
      items: ['getting-started', 'demo-tour', 'architecture', 'faq'],
    },
    {
      type: 'category',
      label: 'Compliance and Controls',
      items: [
        'compliance/regulatory-scope',
        'compliance/fsa-guideline-mapping',
        'compliance/data-retention',
        'case-management',
        'auth',
      ],
    },
    {
      type: 'category',
      label: 'Configure and Tune',
      items: ['configuration', 'rule-authoring'],
    },
    {
      type: 'category',
      label: 'Deploy and Operate',
      items: [
        'operations/deployment',
        'operations/container-images',
        'operations/worker-mode',
        'operations/initial-migration',
        'operations/upgrade',
        'operations/backup-restore',
        'operations/partitioning-guide',
        'operations/dependency-lifecycle',
        'release-notes',
        {
          type: 'category',
          label: 'Troubleshooting',
          items: ['troubleshooting/index', 'troubleshooting/database'],
        },
      ],
    },
    {
      type: 'category',
      label: 'Security and Assurance',
      items: [
        'security/index',
        'security/data-egress',
        'security/supply-chain',
        'security/accepted-risks/index',
      ],
    },
    {
      type: 'category',
      label: 'Integrate and Extend',
      items: [
        'adapter-guide',
        'api/openapi',
        // Generated pages: one per file in content/schema/, so the list is
        // autogenerated rather than enumerated here.
        {type: 'autogenerated', dirName: 'api/schema'},
      ],
    },
    {
      type: 'category',
      label: 'Contribute',
      items: [
        'development/setup',
        'development/testing',
        'development/documentation',
        'development/change-traceability',
        'development/repository-governance',
        'development/release-checklist',
      ],
    },
  ],
};

export default sidebars;
